root: true
extends:
  - "@dhi-gras/ts"
  - "@dhi-gras/react"
rules:
  "@typescript-eslint/unbound-method": 0 # Doesn't appear to read MUI component prop correctly, where the underlying DOM element can be changed, which is the point of the rule
  "@typescript-eslint/no-unsafe-argument": 0
